// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echo/internal/data/ent/bililivesetting"
	"echo/internal/data/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BiliLiveSettingQuery is the builder for querying BiliLiveSetting entities.
type BiliLiveSettingQuery struct {
	config
	ctx        *QueryContext
	order      []bililivesetting.OrderOption
	inters     []Interceptor
	predicates []predicate.BiliLiveSetting
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BiliLiveSettingQuery builder.
func (blsq *BiliLiveSettingQuery) Where(ps ...predicate.BiliLiveSetting) *BiliLiveSettingQuery {
	blsq.predicates = append(blsq.predicates, ps...)
	return blsq
}

// Limit the number of records to be returned by this query.
func (blsq *BiliLiveSettingQuery) Limit(limit int) *BiliLiveSettingQuery {
	blsq.ctx.Limit = &limit
	return blsq
}

// Offset to start from.
func (blsq *BiliLiveSettingQuery) Offset(offset int) *BiliLiveSettingQuery {
	blsq.ctx.Offset = &offset
	return blsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (blsq *BiliLiveSettingQuery) Unique(unique bool) *BiliLiveSettingQuery {
	blsq.ctx.Unique = &unique
	return blsq
}

// Order specifies how the records should be ordered.
func (blsq *BiliLiveSettingQuery) Order(o ...bililivesetting.OrderOption) *BiliLiveSettingQuery {
	blsq.order = append(blsq.order, o...)
	return blsq
}

// First returns the first BiliLiveSetting entity from the query.
// Returns a *NotFoundError when no BiliLiveSetting was found.
func (blsq *BiliLiveSettingQuery) First(ctx context.Context) (*BiliLiveSetting, error) {
	nodes, err := blsq.Limit(1).All(setContextOp(ctx, blsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bililivesetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) FirstX(ctx context.Context) *BiliLiveSetting {
	node, err := blsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BiliLiveSetting ID from the query.
// Returns a *NotFoundError when no BiliLiveSetting ID was found.
func (blsq *BiliLiveSettingQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = blsq.Limit(1).IDs(setContextOp(ctx, blsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bililivesetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) FirstIDX(ctx context.Context) int64 {
	id, err := blsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BiliLiveSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BiliLiveSetting entity is found.
// Returns a *NotFoundError when no BiliLiveSetting entities are found.
func (blsq *BiliLiveSettingQuery) Only(ctx context.Context) (*BiliLiveSetting, error) {
	nodes, err := blsq.Limit(2).All(setContextOp(ctx, blsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bililivesetting.Label}
	default:
		return nil, &NotSingularError{bililivesetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) OnlyX(ctx context.Context) *BiliLiveSetting {
	node, err := blsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BiliLiveSetting ID in the query.
// Returns a *NotSingularError when more than one BiliLiveSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (blsq *BiliLiveSettingQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = blsq.Limit(2).IDs(setContextOp(ctx, blsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bililivesetting.Label}
	default:
		err = &NotSingularError{bililivesetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := blsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BiliLiveSettings.
func (blsq *BiliLiveSettingQuery) All(ctx context.Context) ([]*BiliLiveSetting, error) {
	ctx = setContextOp(ctx, blsq.ctx, ent.OpQueryAll)
	if err := blsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BiliLiveSetting, *BiliLiveSettingQuery]()
	return withInterceptors[[]*BiliLiveSetting](ctx, blsq, qr, blsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) AllX(ctx context.Context) []*BiliLiveSetting {
	nodes, err := blsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BiliLiveSetting IDs.
func (blsq *BiliLiveSettingQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if blsq.ctx.Unique == nil && blsq.path != nil {
		blsq.Unique(true)
	}
	ctx = setContextOp(ctx, blsq.ctx, ent.OpQueryIDs)
	if err = blsq.Select(bililivesetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) IDsX(ctx context.Context) []int64 {
	ids, err := blsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (blsq *BiliLiveSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, blsq.ctx, ent.OpQueryCount)
	if err := blsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, blsq, querierCount[*BiliLiveSettingQuery](), blsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) CountX(ctx context.Context) int {
	count, err := blsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (blsq *BiliLiveSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, blsq.ctx, ent.OpQueryExist)
	switch _, err := blsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (blsq *BiliLiveSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := blsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BiliLiveSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (blsq *BiliLiveSettingQuery) Clone() *BiliLiveSettingQuery {
	if blsq == nil {
		return nil
	}
	return &BiliLiveSettingQuery{
		config:     blsq.config,
		ctx:        blsq.ctx.Clone(),
		order:      append([]bililivesetting.OrderOption{}, blsq.order...),
		inters:     append([]Interceptor{}, blsq.inters...),
		predicates: append([]predicate.BiliLiveSetting{}, blsq.predicates...),
		// clone intermediate query.
		sql:  blsq.sql.Clone(),
		path: blsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoomID int64 `json:"room_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BiliLiveSetting.Query().
//		GroupBy(bililivesetting.FieldRoomID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (blsq *BiliLiveSettingQuery) GroupBy(field string, fields ...string) *BiliLiveSettingGroupBy {
	blsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BiliLiveSettingGroupBy{build: blsq}
	grbuild.flds = &blsq.ctx.Fields
	grbuild.label = bililivesetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoomID int64 `json:"room_id,omitempty"`
//	}
//
//	client.BiliLiveSetting.Query().
//		Select(bililivesetting.FieldRoomID).
//		Scan(ctx, &v)
func (blsq *BiliLiveSettingQuery) Select(fields ...string) *BiliLiveSettingSelect {
	blsq.ctx.Fields = append(blsq.ctx.Fields, fields...)
	sbuild := &BiliLiveSettingSelect{BiliLiveSettingQuery: blsq}
	sbuild.label = bililivesetting.Label
	sbuild.flds, sbuild.scan = &blsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BiliLiveSettingSelect configured with the given aggregations.
func (blsq *BiliLiveSettingQuery) Aggregate(fns ...AggregateFunc) *BiliLiveSettingSelect {
	return blsq.Select().Aggregate(fns...)
}

func (blsq *BiliLiveSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range blsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, blsq); err != nil {
				return err
			}
		}
	}
	for _, f := range blsq.ctx.Fields {
		if !bililivesetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if blsq.path != nil {
		prev, err := blsq.path(ctx)
		if err != nil {
			return err
		}
		blsq.sql = prev
	}
	return nil
}

func (blsq *BiliLiveSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BiliLiveSetting, error) {
	var (
		nodes = []*BiliLiveSetting{}
		_spec = blsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BiliLiveSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BiliLiveSetting{config: blsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, blsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (blsq *BiliLiveSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := blsq.querySpec()
	_spec.Node.Columns = blsq.ctx.Fields
	if len(blsq.ctx.Fields) > 0 {
		_spec.Unique = blsq.ctx.Unique != nil && *blsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, blsq.driver, _spec)
}

func (blsq *BiliLiveSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bililivesetting.Table, bililivesetting.Columns, sqlgraph.NewFieldSpec(bililivesetting.FieldID, field.TypeInt64))
	_spec.From = blsq.sql
	if unique := blsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if blsq.path != nil {
		_spec.Unique = true
	}
	if fields := blsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bililivesetting.FieldID)
		for i := range fields {
			if fields[i] != bililivesetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := blsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := blsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := blsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := blsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (blsq *BiliLiveSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(blsq.driver.Dialect())
	t1 := builder.Table(bililivesetting.Table)
	columns := blsq.ctx.Fields
	if len(columns) == 0 {
		columns = bililivesetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if blsq.sql != nil {
		selector = blsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if blsq.ctx.Unique != nil && *blsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range blsq.predicates {
		p(selector)
	}
	for _, p := range blsq.order {
		p(selector)
	}
	if offset := blsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := blsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BiliLiveSettingGroupBy is the group-by builder for BiliLiveSetting entities.
type BiliLiveSettingGroupBy struct {
	selector
	build *BiliLiveSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (blsgb *BiliLiveSettingGroupBy) Aggregate(fns ...AggregateFunc) *BiliLiveSettingGroupBy {
	blsgb.fns = append(blsgb.fns, fns...)
	return blsgb
}

// Scan applies the selector query and scans the result into the given value.
func (blsgb *BiliLiveSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, blsgb.build.ctx, ent.OpQueryGroupBy)
	if err := blsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BiliLiveSettingQuery, *BiliLiveSettingGroupBy](ctx, blsgb.build, blsgb, blsgb.build.inters, v)
}

func (blsgb *BiliLiveSettingGroupBy) sqlScan(ctx context.Context, root *BiliLiveSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(blsgb.fns))
	for _, fn := range blsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*blsgb.flds)+len(blsgb.fns))
		for _, f := range *blsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*blsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := blsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BiliLiveSettingSelect is the builder for selecting fields of BiliLiveSetting entities.
type BiliLiveSettingSelect struct {
	*BiliLiveSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (blss *BiliLiveSettingSelect) Aggregate(fns ...AggregateFunc) *BiliLiveSettingSelect {
	blss.fns = append(blss.fns, fns...)
	return blss
}

// Scan applies the selector query and scans the result into the given value.
func (blss *BiliLiveSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, blss.ctx, ent.OpQuerySelect)
	if err := blss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BiliLiveSettingQuery, *BiliLiveSettingSelect](ctx, blss.BiliLiveSettingQuery, blss, blss.inters, v)
}

func (blss *BiliLiveSettingSelect) sqlScan(ctx context.Context, root *BiliLiveSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(blss.fns))
	for _, fn := range blss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*blss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := blss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
