// Code generated by ent, DO NOT EDIT.

package ent

import (
	"echo/internal/data/ent/bot"
	"echo/internal/data/ent/schema"
	"echo/internal/data/ent/sub"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	botFields := schema.Bot{}.Fields()
	_ = botFields
	// botDescStatus is the schema descriptor for status field.
	botDescStatus := botFields[5].Descriptor()
	// bot.DefaultStatus holds the default value on creation for the status field.
	bot.DefaultStatus = botDescStatus.Default.(int)
	subFields := schema.Sub{}.Fields()
	_ = subFields
	// subDescStatus is the schema descriptor for status field.
	subDescStatus := subFields[5].Descriptor()
	// sub.DefaultStatus holds the default value on creation for the status field.
	sub.DefaultStatus = subDescStatus.Default.(int)
}
