// Code generated by ent, DO NOT EDIT.

package ent

import (
	"echo/internal/data/ent/subbililive"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SubBiliLive is the model entity for the SubBiliLive schema.
type SubBiliLive struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID int64 `json:"room_id,omitempty"`
	// LiveState holds the value of the "live_state" field.
	LiveState int64 `json:"live_state,omitempty"`
	// LiveStartTime holds the value of the "live_start_time" field.
	LiveStartTime int64 `json:"live_start_time,omitempty"`
	// LiveEndTime holds the value of the "live_end_time" field.
	LiveEndTime int64 `json:"live_end_time,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   time.Time `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubBiliLive) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subbililive.FieldID, subbililive.FieldRoomID, subbililive.FieldLiveState, subbililive.FieldLiveStartTime, subbililive.FieldLiveEndTime:
			values[i] = new(sql.NullInt64)
		case subbililive.FieldCreateTime, subbililive.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubBiliLive fields.
func (sbl *SubBiliLive) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subbililive.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sbl.ID = int64(value.Int64)
		case subbililive.FieldRoomID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value.Valid {
				sbl.RoomID = value.Int64
			}
		case subbililive.FieldLiveState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_state", values[i])
			} else if value.Valid {
				sbl.LiveState = value.Int64
			}
		case subbililive.FieldLiveStartTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_start_time", values[i])
			} else if value.Valid {
				sbl.LiveStartTime = value.Int64
			}
		case subbililive.FieldLiveEndTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_end_time", values[i])
			} else if value.Valid {
				sbl.LiveEndTime = value.Int64
			}
		case subbililive.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				sbl.CreateTime = value.Time
			}
		case subbililive.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				sbl.UpdateTime = value.Time
			}
		default:
			sbl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubBiliLive.
// This includes values selected through modifiers, order, etc.
func (sbl *SubBiliLive) Value(name string) (ent.Value, error) {
	return sbl.selectValues.Get(name)
}

// Update returns a builder for updating this SubBiliLive.
// Note that you need to call SubBiliLive.Unwrap() before calling this method if this SubBiliLive
// was returned from a transaction, and the transaction was committed or rolled back.
func (sbl *SubBiliLive) Update() *SubBiliLiveUpdateOne {
	return NewSubBiliLiveClient(sbl.config).UpdateOne(sbl)
}

// Unwrap unwraps the SubBiliLive entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sbl *SubBiliLive) Unwrap() *SubBiliLive {
	_tx, ok := sbl.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubBiliLive is not a transactional entity")
	}
	sbl.config.driver = _tx.drv
	return sbl
}

// String implements the fmt.Stringer.
func (sbl *SubBiliLive) String() string {
	var builder strings.Builder
	builder.WriteString("SubBiliLive(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sbl.ID))
	builder.WriteString("room_id=")
	builder.WriteString(fmt.Sprintf("%v", sbl.RoomID))
	builder.WriteString(", ")
	builder.WriteString("live_state=")
	builder.WriteString(fmt.Sprintf("%v", sbl.LiveState))
	builder.WriteString(", ")
	builder.WriteString("live_start_time=")
	builder.WriteString(fmt.Sprintf("%v", sbl.LiveStartTime))
	builder.WriteString(", ")
	builder.WriteString("live_end_time=")
	builder.WriteString(fmt.Sprintf("%v", sbl.LiveEndTime))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(sbl.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(sbl.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubBiliLives is a parsable slice of SubBiliLive.
type SubBiliLives []*SubBiliLive
