// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echo/internal/data/ent/predicate"
	"echo/internal/data/ent/subdouyulive"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubDouyuLiveQuery is the builder for querying SubDouyuLive entities.
type SubDouyuLiveQuery struct {
	config
	ctx        *QueryContext
	order      []subdouyulive.OrderOption
	inters     []Interceptor
	predicates []predicate.SubDouyuLive
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubDouyuLiveQuery builder.
func (sdlq *SubDouyuLiveQuery) Where(ps ...predicate.SubDouyuLive) *SubDouyuLiveQuery {
	sdlq.predicates = append(sdlq.predicates, ps...)
	return sdlq
}

// Limit the number of records to be returned by this query.
func (sdlq *SubDouyuLiveQuery) Limit(limit int) *SubDouyuLiveQuery {
	sdlq.ctx.Limit = &limit
	return sdlq
}

// Offset to start from.
func (sdlq *SubDouyuLiveQuery) Offset(offset int) *SubDouyuLiveQuery {
	sdlq.ctx.Offset = &offset
	return sdlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sdlq *SubDouyuLiveQuery) Unique(unique bool) *SubDouyuLiveQuery {
	sdlq.ctx.Unique = &unique
	return sdlq
}

// Order specifies how the records should be ordered.
func (sdlq *SubDouyuLiveQuery) Order(o ...subdouyulive.OrderOption) *SubDouyuLiveQuery {
	sdlq.order = append(sdlq.order, o...)
	return sdlq
}

// First returns the first SubDouyuLive entity from the query.
// Returns a *NotFoundError when no SubDouyuLive was found.
func (sdlq *SubDouyuLiveQuery) First(ctx context.Context) (*SubDouyuLive, error) {
	nodes, err := sdlq.Limit(1).All(setContextOp(ctx, sdlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subdouyulive.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) FirstX(ctx context.Context) *SubDouyuLive {
	node, err := sdlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubDouyuLive ID from the query.
// Returns a *NotFoundError when no SubDouyuLive ID was found.
func (sdlq *SubDouyuLiveQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sdlq.Limit(1).IDs(setContextOp(ctx, sdlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subdouyulive.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) FirstIDX(ctx context.Context) int64 {
	id, err := sdlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubDouyuLive entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubDouyuLive entity is found.
// Returns a *NotFoundError when no SubDouyuLive entities are found.
func (sdlq *SubDouyuLiveQuery) Only(ctx context.Context) (*SubDouyuLive, error) {
	nodes, err := sdlq.Limit(2).All(setContextOp(ctx, sdlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subdouyulive.Label}
	default:
		return nil, &NotSingularError{subdouyulive.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) OnlyX(ctx context.Context) *SubDouyuLive {
	node, err := sdlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubDouyuLive ID in the query.
// Returns a *NotSingularError when more than one SubDouyuLive ID is found.
// Returns a *NotFoundError when no entities are found.
func (sdlq *SubDouyuLiveQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sdlq.Limit(2).IDs(setContextOp(ctx, sdlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subdouyulive.Label}
	default:
		err = &NotSingularError{subdouyulive.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := sdlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubDouyuLives.
func (sdlq *SubDouyuLiveQuery) All(ctx context.Context) ([]*SubDouyuLive, error) {
	ctx = setContextOp(ctx, sdlq.ctx, ent.OpQueryAll)
	if err := sdlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubDouyuLive, *SubDouyuLiveQuery]()
	return withInterceptors[[]*SubDouyuLive](ctx, sdlq, qr, sdlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) AllX(ctx context.Context) []*SubDouyuLive {
	nodes, err := sdlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubDouyuLive IDs.
func (sdlq *SubDouyuLiveQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if sdlq.ctx.Unique == nil && sdlq.path != nil {
		sdlq.Unique(true)
	}
	ctx = setContextOp(ctx, sdlq.ctx, ent.OpQueryIDs)
	if err = sdlq.Select(subdouyulive.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) IDsX(ctx context.Context) []int64 {
	ids, err := sdlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sdlq *SubDouyuLiveQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sdlq.ctx, ent.OpQueryCount)
	if err := sdlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sdlq, querierCount[*SubDouyuLiveQuery](), sdlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) CountX(ctx context.Context) int {
	count, err := sdlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sdlq *SubDouyuLiveQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sdlq.ctx, ent.OpQueryExist)
	switch _, err := sdlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sdlq *SubDouyuLiveQuery) ExistX(ctx context.Context) bool {
	exist, err := sdlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubDouyuLiveQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sdlq *SubDouyuLiveQuery) Clone() *SubDouyuLiveQuery {
	if sdlq == nil {
		return nil
	}
	return &SubDouyuLiveQuery{
		config:     sdlq.config,
		ctx:        sdlq.ctx.Clone(),
		order:      append([]subdouyulive.OrderOption{}, sdlq.order...),
		inters:     append([]Interceptor{}, sdlq.inters...),
		predicates: append([]predicate.SubDouyuLive{}, sdlq.predicates...),
		// clone intermediate query.
		sql:  sdlq.sql.Clone(),
		path: sdlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoomID int64 `json:"room_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubDouyuLive.Query().
//		GroupBy(subdouyulive.FieldRoomID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sdlq *SubDouyuLiveQuery) GroupBy(field string, fields ...string) *SubDouyuLiveGroupBy {
	sdlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubDouyuLiveGroupBy{build: sdlq}
	grbuild.flds = &sdlq.ctx.Fields
	grbuild.label = subdouyulive.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoomID int64 `json:"room_id,omitempty"`
//	}
//
//	client.SubDouyuLive.Query().
//		Select(subdouyulive.FieldRoomID).
//		Scan(ctx, &v)
func (sdlq *SubDouyuLiveQuery) Select(fields ...string) *SubDouyuLiveSelect {
	sdlq.ctx.Fields = append(sdlq.ctx.Fields, fields...)
	sbuild := &SubDouyuLiveSelect{SubDouyuLiveQuery: sdlq}
	sbuild.label = subdouyulive.Label
	sbuild.flds, sbuild.scan = &sdlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubDouyuLiveSelect configured with the given aggregations.
func (sdlq *SubDouyuLiveQuery) Aggregate(fns ...AggregateFunc) *SubDouyuLiveSelect {
	return sdlq.Select().Aggregate(fns...)
}

func (sdlq *SubDouyuLiveQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sdlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sdlq); err != nil {
				return err
			}
		}
	}
	for _, f := range sdlq.ctx.Fields {
		if !subdouyulive.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sdlq.path != nil {
		prev, err := sdlq.path(ctx)
		if err != nil {
			return err
		}
		sdlq.sql = prev
	}
	return nil
}

func (sdlq *SubDouyuLiveQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubDouyuLive, error) {
	var (
		nodes = []*SubDouyuLive{}
		_spec = sdlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubDouyuLive).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubDouyuLive{config: sdlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sdlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sdlq *SubDouyuLiveQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sdlq.querySpec()
	_spec.Node.Columns = sdlq.ctx.Fields
	if len(sdlq.ctx.Fields) > 0 {
		_spec.Unique = sdlq.ctx.Unique != nil && *sdlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sdlq.driver, _spec)
}

func (sdlq *SubDouyuLiveQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subdouyulive.Table, subdouyulive.Columns, sqlgraph.NewFieldSpec(subdouyulive.FieldID, field.TypeInt64))
	_spec.From = sdlq.sql
	if unique := sdlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sdlq.path != nil {
		_spec.Unique = true
	}
	if fields := sdlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subdouyulive.FieldID)
		for i := range fields {
			if fields[i] != subdouyulive.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sdlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sdlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sdlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sdlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sdlq *SubDouyuLiveQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sdlq.driver.Dialect())
	t1 := builder.Table(subdouyulive.Table)
	columns := sdlq.ctx.Fields
	if len(columns) == 0 {
		columns = subdouyulive.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sdlq.sql != nil {
		selector = sdlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sdlq.ctx.Unique != nil && *sdlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sdlq.predicates {
		p(selector)
	}
	for _, p := range sdlq.order {
		p(selector)
	}
	if offset := sdlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sdlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubDouyuLiveGroupBy is the group-by builder for SubDouyuLive entities.
type SubDouyuLiveGroupBy struct {
	selector
	build *SubDouyuLiveQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sdlgb *SubDouyuLiveGroupBy) Aggregate(fns ...AggregateFunc) *SubDouyuLiveGroupBy {
	sdlgb.fns = append(sdlgb.fns, fns...)
	return sdlgb
}

// Scan applies the selector query and scans the result into the given value.
func (sdlgb *SubDouyuLiveGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sdlgb.build.ctx, ent.OpQueryGroupBy)
	if err := sdlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubDouyuLiveQuery, *SubDouyuLiveGroupBy](ctx, sdlgb.build, sdlgb, sdlgb.build.inters, v)
}

func (sdlgb *SubDouyuLiveGroupBy) sqlScan(ctx context.Context, root *SubDouyuLiveQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sdlgb.fns))
	for _, fn := range sdlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sdlgb.flds)+len(sdlgb.fns))
		for _, f := range *sdlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sdlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubDouyuLiveSelect is the builder for selecting fields of SubDouyuLive entities.
type SubDouyuLiveSelect struct {
	*SubDouyuLiveQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sdls *SubDouyuLiveSelect) Aggregate(fns ...AggregateFunc) *SubDouyuLiveSelect {
	sdls.fns = append(sdls.fns, fns...)
	return sdls
}

// Scan applies the selector query and scans the result into the given value.
func (sdls *SubDouyuLiveSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sdls.ctx, ent.OpQuerySelect)
	if err := sdls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubDouyuLiveQuery, *SubDouyuLiveSelect](ctx, sdls.SubDouyuLiveQuery, sdls, sdls.inters, v)
}

func (sdls *SubDouyuLiveSelect) sqlScan(ctx context.Context, root *SubDouyuLiveQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sdls.fns))
	for _, fn := range sdls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sdls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
