// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echo/internal/data/ent/subdouyulive"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubDouyuLiveCreate is the builder for creating a SubDouyuLive entity.
type SubDouyuLiveCreate struct {
	config
	mutation *SubDouyuLiveMutation
	hooks    []Hook
}

// SetRoomID sets the "room_id" field.
func (sdlc *SubDouyuLiveCreate) SetRoomID(i int64) *SubDouyuLiveCreate {
	sdlc.mutation.SetRoomID(i)
	return sdlc
}

// SetLiveState sets the "live_state" field.
func (sdlc *SubDouyuLiveCreate) SetLiveState(i int64) *SubDouyuLiveCreate {
	sdlc.mutation.SetLiveState(i)
	return sdlc
}

// SetLiveStartTime sets the "live_start_time" field.
func (sdlc *SubDouyuLiveCreate) SetLiveStartTime(i int64) *SubDouyuLiveCreate {
	sdlc.mutation.SetLiveStartTime(i)
	return sdlc
}

// SetLiveEndTime sets the "live_end_time" field.
func (sdlc *SubDouyuLiveCreate) SetLiveEndTime(i int64) *SubDouyuLiveCreate {
	sdlc.mutation.SetLiveEndTime(i)
	return sdlc
}

// SetCreateTime sets the "create_time" field.
func (sdlc *SubDouyuLiveCreate) SetCreateTime(t time.Time) *SubDouyuLiveCreate {
	sdlc.mutation.SetCreateTime(t)
	return sdlc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sdlc *SubDouyuLiveCreate) SetNillableCreateTime(t *time.Time) *SubDouyuLiveCreate {
	if t != nil {
		sdlc.SetCreateTime(*t)
	}
	return sdlc
}

// SetUpdateTime sets the "update_time" field.
func (sdlc *SubDouyuLiveCreate) SetUpdateTime(t time.Time) *SubDouyuLiveCreate {
	sdlc.mutation.SetUpdateTime(t)
	return sdlc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sdlc *SubDouyuLiveCreate) SetNillableUpdateTime(t *time.Time) *SubDouyuLiveCreate {
	if t != nil {
		sdlc.SetUpdateTime(*t)
	}
	return sdlc
}

// SetID sets the "id" field.
func (sdlc *SubDouyuLiveCreate) SetID(i int64) *SubDouyuLiveCreate {
	sdlc.mutation.SetID(i)
	return sdlc
}

// Mutation returns the SubDouyuLiveMutation object of the builder.
func (sdlc *SubDouyuLiveCreate) Mutation() *SubDouyuLiveMutation {
	return sdlc.mutation
}

// Save creates the SubDouyuLive in the database.
func (sdlc *SubDouyuLiveCreate) Save(ctx context.Context) (*SubDouyuLive, error) {
	return withHooks(ctx, sdlc.sqlSave, sdlc.mutation, sdlc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sdlc *SubDouyuLiveCreate) SaveX(ctx context.Context) *SubDouyuLive {
	v, err := sdlc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sdlc *SubDouyuLiveCreate) Exec(ctx context.Context) error {
	_, err := sdlc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdlc *SubDouyuLiveCreate) ExecX(ctx context.Context) {
	if err := sdlc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sdlc *SubDouyuLiveCreate) check() error {
	if _, ok := sdlc.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "SubDouyuLive.room_id"`)}
	}
	if _, ok := sdlc.mutation.LiveState(); !ok {
		return &ValidationError{Name: "live_state", err: errors.New(`ent: missing required field "SubDouyuLive.live_state"`)}
	}
	if _, ok := sdlc.mutation.LiveStartTime(); !ok {
		return &ValidationError{Name: "live_start_time", err: errors.New(`ent: missing required field "SubDouyuLive.live_start_time"`)}
	}
	if _, ok := sdlc.mutation.LiveEndTime(); !ok {
		return &ValidationError{Name: "live_end_time", err: errors.New(`ent: missing required field "SubDouyuLive.live_end_time"`)}
	}
	return nil
}

func (sdlc *SubDouyuLiveCreate) sqlSave(ctx context.Context) (*SubDouyuLive, error) {
	if err := sdlc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sdlc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sdlc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sdlc.mutation.id = &_node.ID
	sdlc.mutation.done = true
	return _node, nil
}

func (sdlc *SubDouyuLiveCreate) createSpec() (*SubDouyuLive, *sqlgraph.CreateSpec) {
	var (
		_node = &SubDouyuLive{config: sdlc.config}
		_spec = sqlgraph.NewCreateSpec(subdouyulive.Table, sqlgraph.NewFieldSpec(subdouyulive.FieldID, field.TypeInt64))
	)
	if id, ok := sdlc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sdlc.mutation.RoomID(); ok {
		_spec.SetField(subdouyulive.FieldRoomID, field.TypeInt64, value)
		_node.RoomID = value
	}
	if value, ok := sdlc.mutation.LiveState(); ok {
		_spec.SetField(subdouyulive.FieldLiveState, field.TypeInt64, value)
		_node.LiveState = value
	}
	if value, ok := sdlc.mutation.LiveStartTime(); ok {
		_spec.SetField(subdouyulive.FieldLiveStartTime, field.TypeInt64, value)
		_node.LiveStartTime = value
	}
	if value, ok := sdlc.mutation.LiveEndTime(); ok {
		_spec.SetField(subdouyulive.FieldLiveEndTime, field.TypeInt64, value)
		_node.LiveEndTime = value
	}
	if value, ok := sdlc.mutation.CreateTime(); ok {
		_spec.SetField(subdouyulive.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := sdlc.mutation.UpdateTime(); ok {
		_spec.SetField(subdouyulive.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	return _node, _spec
}

// SubDouyuLiveCreateBulk is the builder for creating many SubDouyuLive entities in bulk.
type SubDouyuLiveCreateBulk struct {
	config
	err      error
	builders []*SubDouyuLiveCreate
}

// Save creates the SubDouyuLive entities in the database.
func (sdlcb *SubDouyuLiveCreateBulk) Save(ctx context.Context) ([]*SubDouyuLive, error) {
	if sdlcb.err != nil {
		return nil, sdlcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sdlcb.builders))
	nodes := make([]*SubDouyuLive, len(sdlcb.builders))
	mutators := make([]Mutator, len(sdlcb.builders))
	for i := range sdlcb.builders {
		func(i int, root context.Context) {
			builder := sdlcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubDouyuLiveMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sdlcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sdlcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sdlcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sdlcb *SubDouyuLiveCreateBulk) SaveX(ctx context.Context) []*SubDouyuLive {
	v, err := sdlcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sdlcb *SubDouyuLiveCreateBulk) Exec(ctx context.Context) error {
	_, err := sdlcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdlcb *SubDouyuLiveCreateBulk) ExecX(ctx context.Context) {
	if err := sdlcb.Exec(ctx); err != nil {
		panic(err)
	}
}
