// Code generated by ent, DO NOT EDIT.

package ent

import (
	"echo/internal/data/ent/subdouyulive"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SubDouyuLive is the model entity for the SubDouyuLive schema.
type SubDouyuLive struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID int64 `json:"room_id,omitempty"`
	// LiveState holds the value of the "live_state" field.
	LiveState int64 `json:"live_state,omitempty"`
	// LiveStartTime holds the value of the "live_start_time" field.
	LiveStartTime int64 `json:"live_start_time,omitempty"`
	// LiveEndTime holds the value of the "live_end_time" field.
	LiveEndTime int64 `json:"live_end_time,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   time.Time `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubDouyuLive) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subdouyulive.FieldID, subdouyulive.FieldRoomID, subdouyulive.FieldLiveState, subdouyulive.FieldLiveStartTime, subdouyulive.FieldLiveEndTime:
			values[i] = new(sql.NullInt64)
		case subdouyulive.FieldCreateTime, subdouyulive.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubDouyuLive fields.
func (sdl *SubDouyuLive) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subdouyulive.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sdl.ID = int64(value.Int64)
		case subdouyulive.FieldRoomID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value.Valid {
				sdl.RoomID = value.Int64
			}
		case subdouyulive.FieldLiveState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_state", values[i])
			} else if value.Valid {
				sdl.LiveState = value.Int64
			}
		case subdouyulive.FieldLiveStartTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_start_time", values[i])
			} else if value.Valid {
				sdl.LiveStartTime = value.Int64
			}
		case subdouyulive.FieldLiveEndTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_end_time", values[i])
			} else if value.Valid {
				sdl.LiveEndTime = value.Int64
			}
		case subdouyulive.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				sdl.CreateTime = value.Time
			}
		case subdouyulive.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				sdl.UpdateTime = value.Time
			}
		default:
			sdl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubDouyuLive.
// This includes values selected through modifiers, order, etc.
func (sdl *SubDouyuLive) Value(name string) (ent.Value, error) {
	return sdl.selectValues.Get(name)
}

// Update returns a builder for updating this SubDouyuLive.
// Note that you need to call SubDouyuLive.Unwrap() before calling this method if this SubDouyuLive
// was returned from a transaction, and the transaction was committed or rolled back.
func (sdl *SubDouyuLive) Update() *SubDouyuLiveUpdateOne {
	return NewSubDouyuLiveClient(sdl.config).UpdateOne(sdl)
}

// Unwrap unwraps the SubDouyuLive entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sdl *SubDouyuLive) Unwrap() *SubDouyuLive {
	_tx, ok := sdl.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubDouyuLive is not a transactional entity")
	}
	sdl.config.driver = _tx.drv
	return sdl
}

// String implements the fmt.Stringer.
func (sdl *SubDouyuLive) String() string {
	var builder strings.Builder
	builder.WriteString("SubDouyuLive(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sdl.ID))
	builder.WriteString("room_id=")
	builder.WriteString(fmt.Sprintf("%v", sdl.RoomID))
	builder.WriteString(", ")
	builder.WriteString("live_state=")
	builder.WriteString(fmt.Sprintf("%v", sdl.LiveState))
	builder.WriteString(", ")
	builder.WriteString("live_start_time=")
	builder.WriteString(fmt.Sprintf("%v", sdl.LiveStartTime))
	builder.WriteString(", ")
	builder.WriteString("live_end_time=")
	builder.WriteString(fmt.Sprintf("%v", sdl.LiveEndTime))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(sdl.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(sdl.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubDouyuLives is a parsable slice of SubDouyuLive.
type SubDouyuLives []*SubDouyuLive
