// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bot is the predicate function for bot builders.
type Bot func(*sql.Selector)

// Sub is the predicate function for sub builders.
type Sub func(*sql.Selector)

// SubBiliLive is the predicate function for subbililive builders.
type SubBiliLive func(*sql.Selector)

// SubDouyuLive is the predicate function for subdouyulive builders.
type SubDouyuLive func(*sql.Selector)
