// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BiliLiveSetting is the predicate function for bililivesetting builders.
type BiliLiveSetting func(*sql.Selector)

// Bot is the predicate function for bot builders.
type Bot func(*sql.Selector)
