// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"echo/internal/biz"
	"echo/internal/command"
	"echo/internal/data"
	"echo/internal/service"
	"echo/pkg/app"
	"echo/pkg/bot"
	"echo/pkg/logger"
)

// Injectors from wire.go:

func wireApp(log *logger.Logger) (*app.App, error) {
	echoService := service.NewEchoService()
	commandRegistry := command.NewInitializedRegistry(echoService)
	dataData, err := data.NewData()
	if err != nil {
		return nil, err
	}
	botRepo := data.NewBotRepo(dataData)
	botUsecase := biz.NewBotUsecase(botRepo)
	handler := bot.NewBotHandler(commandRegistry, log, botUsecase)
	botBot := bot.NewBot(handler)
	appApp := app.NewApp(botBot, log)
	return appApp, nil
}
