// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"echo/internal/app"
	"echo/internal/biz"
	"echo/internal/command"
	"echo/internal/data"
	"echo/internal/service"
	"echo/pkg/logger"
)

// Injectors from wire.go:

func wireApp(log *logger.Logger) (*app.Bot, error) {
	dataData, err := data.NewData()
	if err != nil {
		return nil, err
	}
	botRepo := data.NewBotRepo(dataData)
	botUsecase := biz.NewBotUsecase(botRepo)
	setMasterService := service.NewSetMasterService(botUsecase)
	commandRegistry := command.NewInitializedRegistry(setMasterService)
	handler := app.NewBotHandler(commandRegistry, log, botUsecase)
	bot := app.NewBot(handler)
	return bot, nil
}
