// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BotsColumns holds the columns for the "bots" table.
	BotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "bot_id", Type: field.TypeInt64},
		{Name: "bot_name", Type: field.TypeString},
		{Name: "self_id", Type: field.TypeInt64},
		{Name: "access_token", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt, Default: 1},
		{Name: "last_online_time", Type: field.TypeTime},
		{Name: "last_online_ip", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// BotsTable holds the schema information for the "bots" table.
	BotsTable = &schema.Table{
		Name:       "bots",
		Columns:    BotsColumns,
		PrimaryKey: []*schema.Column{BotsColumns[0]},
	}
	// SubsColumns holds the columns for the "subs" table.
	SubsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "sub_type", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64},
		{Name: "sub_id", Type: field.TypeInt64},
		{Name: "bot_id", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeInt, Default: 1},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// SubsTable holds the schema information for the "subs" table.
	SubsTable = &schema.Table{
		Name:       "subs",
		Columns:    SubsColumns,
		PrimaryKey: []*schema.Column{SubsColumns[0]},
	}
	// SubBiliLiveColumns holds the columns for the "sub_bili_live" table.
	SubBiliLiveColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "room_id", Type: field.TypeInt64},
		{Name: "live_state", Type: field.TypeInt64},
		{Name: "live_start_time", Type: field.TypeInt64},
		{Name: "live_end_time", Type: field.TypeInt64},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// SubBiliLiveTable holds the schema information for the "sub_bili_live" table.
	SubBiliLiveTable = &schema.Table{
		Name:       "sub_bili_live",
		Columns:    SubBiliLiveColumns,
		PrimaryKey: []*schema.Column{SubBiliLiveColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BotsTable,
		SubsTable,
		SubBiliLiveTable,
	}
)

func init() {
	SubBiliLiveTable.Annotation = &entsql.Annotation{
		Table: "sub_bili_live",
	}
}
